name: test_base_flutter
description: TestBase for flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.18
  dartz: ^0.10.1
  flutter_bloc: ^8.1.2
  flutter_native_timezone: ^2.0.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.4
  mask_text_input_formatter: ^2.4.0
  pull_to_refresh: ^2.0.0
  go_router: ^6.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/dictionaries/
